name: PR Label Checklists

on:
  pull_request_target:
    types: [opened, reopened, labeled, unlabeled]
  issue_comment:
    types: [edited]

concurrency:
  group: pr-checklist-${{ github.event.pull_request.number || github.event.issue.number }}
  cancel-in-progress: true

jobs:
  checklist:
    permissions:
      pull-requests: write
      statuses: write
    uses: sashacmc/ci/.github/workflows/pr-label-checklists.yml@main
